// <auto-generated />
namespace SMA.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dropTable_Nome : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropTable_Nome));
        
        string IMigrationMetadata.Id
        {
            get { return "202105171647258_dropTable_Nome"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
